### PR TITLE
feat: release for version 2.4.0 of the spec

### PR DESCRIPTION
**Pull request by smoya**
This PR is created upfront to reflect on a daily basis what things are included in the release.

Also, the reason to create this PR a long time before the release is to enable automation (bot keeps upstream branches always up to date with master, see this [action](https://github.com/asyncapi/spec/blob/master/.github/workflows/autoupdate.yml)) that we have in place to regularly update the release branch with whatever is changed in the master branch. So nobody has to do it manually.

### CODE REVIEW

**Comment by smoya** [comment]
@magicmatatjahu would you mind merging `master` branch into `2022-04-release` right directly in `2022-04-release` branch without PR? Otherwise, we will keep having the same issue we faced in https://github.com/asyncapi/spec/pull/740#issuecomment-1110854100 ?

**Comment by smoya** [comment]
@magicmatatjahu thanks

**Review by magicmatatjahu — APPROVED** [review]

**Review by magicmatatjahu — APPROVED** [review]

**Pull request merged**
