### PR TITLE
chore: update next-spec branch with master changes

### PR DESCRIPTION
**Pull request by char0n**
This is PR is part of https://github.com/asyncapi/spec/issues/830 and updates `next-spec` branch with changes from `master`.

### CODE REVIEW

**Comment by char0n** [comment]
@fmvilas @derberg @jonaslagoni @magicmatatjahu can you please look into this PR. It's part of 2.5.0 release effort and updates the release branch (`next-spec`) with `master` branch.

**Review by derberg — COMMENTED** [review]
strange to see changes only in `package-lock.json`

GH is not able to load diff for me, what is in there?

**Comment by char0n** [comment]
@derberg there was conflict in `package-lock.json` file between `master` and `next-spec`. I did try to resolve using git diff tool the I've always ended up with corrupted `package-lock.json`. So I've decided to regenerate it using node v16.15.1 (npm v8.11.0) and following command:

```sh
  $ npm i --verbose --legacy-peer-deps
```

**Comment by derberg** [comment]
@char0n weird, there should not be any conflicts, we should just take 1:1 what is in the `master` as I don't think there should be any changes in the `next-spec` related to dependencies

**Comment by char0n** [comment]
> @char0n weird, there should not be any conflicts, we should just take 1:1 what is in the `master` as I don't think there should be any changes in the `next-spec` related to dependencies

@derberg you can try for yourself by checking into `next-spec` branch and running `git merge master`. Just make sure both branches are up-todate.

Anyway, I've tried to eliminate the `package-lock.json` diff by copying it's content from `master` during conflict resolution and running `npm i` to regenerate only actual changes from `package.json` instead of regenerating it all. You are now able to inspect the diff in package-lock.json file.

**Comment by char0n** [comment]
And the windows memory is now passing as well.

**Review by derberg — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
