### PR TITLE
chore: point @asyncapi/specs package to 2.14.0-2022-04-release.1

### PR DESCRIPTION
**Pull request by smoya**
Wondering if I could use some wildcard to not having to do this change every time we wanna merge a change.

### CODE REVIEW

**Comment by derberg** [comment]
yeah, we always tag releases - it should be `2022-04-release`
https://www.npmjs.com/package/@asyncapi/specs

but tbh I do not think it will do what you need, as package-lock will anyway lock to specific version, and without update there, it will still use the “old one”

**Review by derberg — APPROVED** [review]

**Comment by smoya** [comment]
> yeah, we always tag releases - it should be `2022-04-release`
> https://www.npmjs.com/package/@asyncapi/specs
> 
> but tbh I do not think it will do what you need, as package-lock will anyway lock to specific version, and without update there, it will still use the “old one”

Yeah, right. A manual `npm i` will be neded.

**Comment by derberg** [comment]
@smoya I just noticed you did it as `chore` so release candidate with it was not released 😄

**Comment by smoya** [comment]
> @smoya I just noticed you did it as `chore` so release candidate with it was not released 😄

Facepalming but https://github.com/asyncapi/parser-js/pull/522

**Pull request merged**
