### PR TITLE
fix: semicolon fix

### LINKED ISSUE #378: Remove unnecessary semicolon.
https://sonarcloud.io/project/issues?id=asyncapi_parser-js&issues=AXerX_hNhZtDGtobF1Sh&open=AXerX_hNhZtDGtobF1Sh

### PR DESCRIPTION
**Pull request by prahuljose**
**Description**

Removed extra semicolon on line 110

**Related issue(s)**
Resolves #378

### CODE REVIEW

**Comment by prahuljose** [comment]
hi, what do i need to do?

**Comment by magicmatatjahu** [comment]
@prahuljose Please read comment https://github.com/asyncapi/parser-js/pull/380#issuecomment-932245438 :)

**Comment by prahuljose** [comment]
> @prahuljose Please read comment [#380 (comment)](https://github.com/asyncapi/parser-js/pull/380#issuecomment-932245438) :)

Hmm, okay, we'll just wait for @derberg final decision :)

**Comment by derberg** [comment]
Closing this PR. Please have a look at my comment here https://github.com/asyncapi/parser-js/pull/380#issuecomment-933192626

Don't worry @prahuljose, we have many other issues to pick up https://docs.google.com/spreadsheets/d/17YYe-ZompcuUACfCGa8Pc3XunFfWRBrNllIBChJ0yWw

**Pull request closed without merging**
