### PR TITLE
ci: add cli to ignore repos in bump workflow

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

As in title: add cli to ignore repos in bump workflow.

**Related issue(s)**
See https://github.com/asyncapi/cli/pull/376#issuecomment-1408733804

### CODE REVIEW

**Comment by derberg** [comment]
@magicmatatjahu changes in this PR should be done in the other one, and changes from the other one in this one

What is the plan? is RC supposed to be updated in all the AsyncAPI projects or only cli, modelina, studio?

**Comment by magicmatatjahu** [comment]
> changes in this PR should be done in the other one, and changes from the other one in this one

Why? One PR should release `next-major` version in some repos, in another repos we should still bump `parser-js` from master.

**Comment by derberg** [comment]
- then in `next-major` make sure workflow reacts on `next-major` and ignores repos that do not use 2.0 (like `html-template`)
- then in `master` make sure workflow reacts on `master` and ignores repos that use 2.0 (like `cli`)

**Comment by magicmatatjahu** [comment]
@derberg Done, please check :)

**Review by derberg — APPROVED** [review]

**Pull request merged**
