### PR TITLE
fix: precompile ajv

### PR DESCRIPTION
**Pull request by nictownsend**
**Description**

- Pre compile schema validators to avoid need for `unsafe-eval` CSP when using in browser

**Related issue(s)**
See #464

### CODE REVIEW

**Comment by derberg** [comment]
@nictownsend I saw https://github.com/asyncapi/parser-js/issues/460 and this PR but you left it as Draft. For the record we do not look in Draft PRs as they are not even tested, unless you explicitly call for help 😄

**Comment by derberg** [comment]
@nictownsend yo, not sure if you want to continue working on this one as this is still a `Draft` and has many conflicts

**Comment by nictownsend** [comment]
@derberg apologies, I inadvertently disabled notifications from repos - will triage the state of this PR today

**Comment by derberg** [comment]
@nictownsend no worries. Just please take into consideration that there is a advanced work on parser 2.0, so you might want to have a look at brach `next-major`

**Pull request closed without merging**
