### PR TITLE
feat: release for version 3.0.0 of the spec

### PR DESCRIPTION
**Pull request by smoya**
This PR is created upfront to reflect on a daily basis what things are included in the release.

Also, the reason to create this PR a long time before the release is to enable automation (bot keeps upstream branches always up to date with master) that we have in place to regularly update the release branch with whatever is changed in the master branch. So nobody has to do it manually.

### CODE REVIEW

**Comment by jonaslagoni** [comment]
What the f... 😆

**Comment by jonaslagoni** [comment]
@smoya might want to mark this as a draft? 🤔

**Comment by smoya** [comment]
@jonaslagoni I'm not sure if CI automation for upstream branches applies to draft PR's. I think it does https://github.com/asyncapi/parser-js/blob/master/.github/workflows/autoupdate.yml ?

Let's see.

**Pull request closed without merging**
