### PR TITLE
Docs: Update README.md with requirements

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
Since we have a github link as a dependency we must define Git as a requirement.

**Related issue(s)**
This originates from https://github.com/asyncapi/generator/issues/389

### CODE REVIEW

**Comment by jonaslagoni** [comment]
> Not sure we should add anything here. The dependency is temporary and will soon be changed by a regular npm package. What about adding it if someone faces this issue?

Hmm, I mean now that we know its a requirement why waste someone's time debugging when we have the answer. I know it's temporary, but I also know temporary things have a way of staying temporary for quite some time. And if we can save a person an hour debugging etc with a temporary requirement in the README I feel like its worth it 😄

**Comment by fmvilas** [comment]
Fair point

**Comment by derberg** [comment]
I added a comment on this one here https://github.com/asyncapi/generator/issues/389#issuecomment-664475557 that we should not update the readme imho

**Comment by derberg** [comment]
@jonaslagoni closing since we are not using fork anymore https://github.com/asyncapi/parser-js/pull/134

**Pull request closed without merging**
