### PR TITLE
chore(deps): bump ajv to 8.17.1

### PR DESCRIPTION
**Pull request by aeworxet**
This PR upgrades `ajv` to version `8.17.1` to [lay the foundation](https://github.com/asyncapi/parser-js/issues/980#issuecomment-2227599634) for fixing https://github.com/asyncapi/parser-js/issues/980.

Related to https://github.com/asyncapi/parser-js/issues/1012

### CODE REVIEW

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by smoya** [comment]
@aeworxet If we want to release this, you will need to include a changesets file under `.changeset` dir. Copying what the changesets-bot would tell you here (not in this PR because I just installed few mins ago).


Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. If these changes should result in a version bump, you need to add a changeset.

This PR includes no changesets
When changesets are added to this PR, you'll see the packages that this PR includes changesets for and the associated semver types

[Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).

[Click here if you're a maintainer who wants to add a changeset to this PR](https://github.com/aeworxet/asyncapi-parser-js/new/chore-deps-bump-ajv-to-8.17.1?filename=.changeset/unlucky-kids-rush.md&value=---%0A%22@asyncapi/parser%22%3A%20patch%0A---%0A%0Achore%3A%20bump%20ajv%20to%208.17.1%20%0A)

**Comment by aeworxet** [comment]
```bash
$ npx changeset
npm ERR! could not determine executable to run


$ npm install npx -g --force
npm WARN using --force Recommended protections disabled.
npm WARN deprecated npx@10.2.2: This package is now part of the npm CLI.

added 1 package in 3s

1 package is looking for funding
  run `npm fund` for details


$ npx changeset
npm ERR! cb.apply is not a function
```
🤷🏻

@ayushnau ?

**Comment by ayushnau** [comment]
the command for the cli to create changeset is this ```js npx -p @changesets/cli changeset ```

**Comment by aeworxet** [comment]
Should command `npx -p @changesets/cli changeset` be written in a README somewhere? I wouldn't know it if @ayushnau didn't tell.

```bash
$ grep -iHr changesets/cli .
./node_modules/eslint-plugin-prettier/package.json:    "@changesets/cli": "^2.27.1",
./.github/workflows/release-with-changesets.yml:          version: npx -p @changesets/cli changeset version
./.github/workflows/release-with-changesets.yml:          publish: npx -p @changesets/cli changeset publish
```

**Comment by smoya** [comment]
> Click here if you're a maintainer who wants to add another changeset to this PR

Sure, feel free to add it.
BTW, you have a link in https://github.com/asyncapi/parser-js/pull/1042#issuecomment-2250005327 that redirects you to create the file.

**Comment by aeworxet** [comment]
https://github.com/asyncapi/parser-js/pull/1042#issuecomment-2250005327 redirects to

> Run `npx changeset` or `yarn changeset`

while @ayushnau pointed to

> `npx -p @changesets/cli changeset`

That's why I thought this matter needed clarification. :shrug:


Anyway, I've already added the changeset because I need to specify a new version of `@asyncapi/parser` in PR for both `Studio`s; can this PR be merged?

**Comment by smoya** [comment]
> https://github.com/asyncapi/parser-js/pull/1042#issuecomment-2250005327 redirects to
> 
> > Run `npx changeset` or `yarn changeset`
> 
> while @ayushnau pointed to
> 
> > `npx -p @changesets/cli changeset`
> 
> That's why I thought this matter needed clarification. :shrug:
> 
> 
> Anyway, I've already added the changeset because I need to specify a new version of `@asyncapi/parser` in PR for both `Studio`s; can this PR be merged?

The last link of such comment redirects you right directly to the changeset file creation: https://github.com/aeworxet/asyncapi-parser-js/new/chore-deps-bump-ajv-to-8.17.1?filename=.changeset/mean-mice-buy.md&value=---%0A%22%40asyncapi%2Fparser%22%3A%20patch%0A---%0A%0Achore(deps)%3A%20bump%20ajv%20to%208.17.1%0A
Next time you can use it.

**Review by smoya — APPROVED** [review]

**Pull request merged**
