### PR TITLE
chore: merge next-major branch

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- merge `next-major` branch to `next-major-spec`.

### CODE REVIEW

**Review by jonaslagoni — APPROVED** [review]
Remember not to squash merge this 🙂

**Comment by magicmatatjahu** [comment]
@jonaslagoni How?! 😆 

image

**Comment by jonaslagoni** [comment]
Have to change settings 🙂

**Comment by smoya** [comment]
We should move into this but with an up-to-date branch.

**Comment by jonaslagoni** [comment]
Already solved in https://github.com/asyncapi/parser-js/pull/787

**Pull request closed without merging**
