### PR TITLE
ci: set next-major branch as base branch for bump action

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This PR changes the base branch for the bump action so it only applies to dependants of the`next-major` branch, a branch that was recently created to work on the next major version (https://github.com/asyncapi/parser-js/issues/401).

Note that the target branch is (and should be) `next-major`. 

**Related issue(s)**
https://github.com/asyncapi/parser-js/issues/401

### CODE REVIEW

**Comment by smoya** [comment]
I need to confirm this PR does what I expect it does. Would you @derberg mind clarifying the following? 🙏 

Any change made to `next-major` branch needed to be released by semantic-release, will trigger a version bump on all repositories that depend on that `next-major` release tag. Is that right?
On the other side, `next-major` branch would need to stay up-to-date with `master`. Is this something done automatically by any other action, or rather we need to update it manually?

Thanks!

**Comment by smoya** [comment]
Branch is now up-to-date with `master` so by what @derberg mentioned in https://github.com/asyncapi/parser-js/pull/468#issuecomment-1035270509, it seems we are good to go now.

**Comment by smoya** [comment]
Wait... why did the bot merged this PR when there was no 👍  from any Code Owner 🤯  ????? I added the `/rtm` because in case an Owner approved it, to get it merged automatically (as there was nothing else from my side to change).

**Comment by smoya** [comment]
Pinging Code Owners @fmvilas @magicmatatjahu @jonaslagoni @derber.

I think some config is missing in this repository regarding branch protection. A PR shouldn't be merged if there is no +1 of at least one Code Owner. This should be configured in the repository settings, under branch protection rules iirc.

**Comment by magicmatatjahu** [comment]
Why did you remove `next-branch`? I think that we can always change config for given branch if branch exists 😅

**Comment by jonaslagoni** [comment]
> I think some config is missing in this repository regarding branch protection. A PR shouldn't be merged if there is no +1 of at least one Code Owner. This should be configured in the repository settings, under branch protection rules iirc.

It should 👍

**Pull request merged**
