### PR TITLE
chore: update v3 models

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Update v3 models:
- update v3 spec types (TS types)
- add models from https://github.com/asyncapi/spec/pull/847
- add server fields from https://github.com/asyncapi/spec/pull/888
- update SecurityScheme model in v3 version 
- add unit tests

**Related issue(s)**
See also https://github.com/asyncapi/spec/pull/847

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@magicmatatjahu want this reviewed now, or later?

**Comment by magicmatatjahu** [comment]
@jonaslagoni Still spec PRs related to changes are not closed, so we can wait for it, but thanks!

**Comment by magicmatatjahu** [comment]
@jonaslagoni @smoya We can merge that PR. It contains about 90% needed changes for v3 models (based on v3 spec). Then we can add the missing stuff with rules.

**Review by smoya — APPROVED** [review]
~LGTM! 🚀🌔~

Read https://github.com/asyncapi/parser-js/issues/585#issuecomment-1504678582

**Comment by smoya** [comment]
@fmvilas @jonaslagoni can you please review? I did, but I'm still not owner

**Review by smoya — CHANGES_REQUESTED** [review]
https://github.com/asyncapi/parser-js/issues/585#issuecomment-1504678582

**Review by fmvilas — APPROVED** [review]
LGTM 👍

**Review by jonaslagoni — APPROVED** [review]

**Pull request merged**
