### PR TITLE
feat!: release 2.0.0

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This PR contains all the commits that have been merged into `next-major` branch for the `2.0.0` version of the parser.

Something we might want to think about is the fact this PR will be merged by `squash merging`, meaning only one commit will be left, losing each of the individual commits with features, including  the authors. It doesn't feel correct if we merge this commit and all the work ends up being attributed to myself (because I opened this PR).

cc @derberg @fmvilas 

**Related issue(s)**
https://github.com/asyncapi/parser-js/issues/481

### CODE REVIEW

**Review by jonaslagoni — APPROVED** [review]
👍

**Review by derberg — APPROVED** [review]

**Comment by smoya** [comment]
> maybe wait with release for [asyncapi/spec-json-schemas#389](https://github.com/asyncapi/spec-json-schemas/pull/389) and further update in parser to use new API of the `@asyncapi/specs` package

Please review 🙏 https://github.com/asyncapi/parser-js/pull/767

**Review by jonaslagoni — APPROVED** [review]
🔥

**Pull request merged**
