### PR TITLE
feat: release for version 2.6.0 of the spec

### PR DESCRIPTION
**Pull request by AceTheCreator**
Refs https://github.com/asyncapi/spec/issues/894

### CODE REVIEW

**Comment by derberg** [comment]
@AceTheCreator
PR is ready for release imho

**Review by derberg — DISMISSED** [review]

**Comment by derberg** [comment]
@AceTheCreator in theory it is good. It will need to be updated after the merge of https://github.com/asyncapi/spec-json-schemas/pull/307 (as this will trigger a package release) that we need to bump in parser

**Review by fmvilas — APPROVED** [review]

**Review by derberg — APPROVED** [review]

**Pull request merged**
