### PR TITLE
chore: update next-spec with latest master

### PR DESCRIPTION
**Pull request by AceTheCreator**
This PR updates next-spec branch with changes from master.

cc @fmvilas @derberg

### CODE REVIEW

**Review by derberg — APPROVED** [review]

**Review by fmvilas — APPROVED** [review]

**Comment by fmvilas** [comment]
🤔 We got a failing test. Any idea why this is happening? @magicmatatjahu

**Comment by fmvilas** [comment]
Anyway, this is not a concern of this PR so feel free to merge. Remember to merge using the "Merge commit" strategy instead of the "Squash and merge" one.

**Comment by magicmatatjahu** [comment]
@fmvilas

> We got a failing test. Any idea why this is happening?

I don't know 🤷🏼 I don't think so that in the failing test the ajv try to create the new reference for each validation function. I have to check that, so yeah, please merge it and I will apply fix (probably on release branch).

**Comment by AceTheCreator** [comment]
I think I need your approvals @magicmatatjahu, @jonaslagoni

**Review by magicmatatjahu — DISMISSED** [review]

**Comment by fmvilas** [comment]
Yeah, we can't merge if this test is not passing. We should be fixing it on another PR pointing to `next-spec`.

**Comment by magicmatatjahu** [comment]
@AceTheCreator Please add new commits from master and try to merge it :)

**Comment by AceTheCreator** [comment]
All tests passed, thanks to @magicmatatjahu

Kindly review this PR @fmvilas @derberg

**Review by magicmatatjahu — APPROVED** [review]

**Pull request merged**
