### PR TITLE
chore: Cleanup GitHub Actions workflows

### LINKED ISSUE #174: Cleanup GitHub Actions workflows
**Context**

1. We want to make sure we have healthy community and people respec each other in GitHub. We want to monitor all comments in every repository and analyze sentiments to identify negative ones and get proper notification. Idea is to use GitHub Actions for it, to check sentiments with Google Natural Language API and post negative comments to Slack for review.

2. We manage community files in global `.github` repo, and we have GitHub Funding config file there too. As a result we need to cleanup all the repos to remove `.github/FUNDING.yml`

3. Start supporting new GitHub [pull request event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) that allows gives access to `GITHUB_TOKEN` with write access. Fix welcome contributors workflow is needed.

4. We want to automatically merge Pull Requests that are submitted by [Dependanbot](https://dependabot.com/). New workflow needs to be added, or if already existins it needs to be modified

**Description**

1. Add this workflow file called `sentiment-analysis.yml` to `.github/workflows` (create it if it doesn't exist yet) directory: https://gist.github.com/derberg/ab362e4b37f542e7e1813e67b7cb11ee
    Proper secrets are already added to GitHub organization so it is as simple as adding above file to workflows dir.
2. Remove `.github/FUNDING.yml` if it exists
3. If not done already rename `pull_request` from line 4 to `pull_request_target` in `.github/workflows/welcome-first-time-contrib.yml` file
4. Create new file called `automerge.yml` with the following content: https://gist.github.com/derberg/024814a26959d54f683e7bd68d68f007
    If the repository already has a file called `automerge-release-pr-bump.yml` than rename it and adjust `if` statements to check `github.actor == 'asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'` instead of `github.actor == 'asyncapi-bot'`

### PR DESCRIPTION
**Pull request by DanielChuDC**
**Description**

1. Added `sentiment-analysis.yml` to .github/workflows

2. Rename pull_request from line 4 to pull_request_target in .github/workflows/welcome-first-time-contrib.yml file

3. Rename the `automerge-release-pr-bump.yml`to `automerge.yml` and modify the if statement according to the instruction

**Related issue(s)**
Fixes #174

### CODE REVIEW

**Review by derberg — APPROVED** [review]
Thanks! In case you are interested in more contributions then have a look at https://www.asyncapi.com/blog/hacktoberfest-2020

We maintain the list of all hacktoberfest issues here https://docs.google.com/spreadsheets/d/1vX4J395apexutfQ0OSqPNltFKDacmemHZwCmOXwHNLo

**Comment by DanielChuDC** [comment]
can I reopen the issue?

**Comment by derberg** [comment]
@DanielChuDC no need to, you can create a PR without an issue

**Comment by DanielChuDC** [comment]
alright! I open a new issue and link it here too

**Comment by magicmatatjahu** [comment]
@all-contributors please add @DanielChuDC for infra

**Pull request merged**
