### PR TITLE
fix: always allow schema string examples

### PR DESCRIPTION
**Pull request by timonback**
**Description**

The spectral rule asyncApi2SchemaValidation currently enforces that all examples have the same type as the schema type. However, we believe that there are cases in AsyncAPI, where it is needed to accept string examples regardless of the schema type.

_To Reproduce:_

1. Use the AsyncAPI document: https://github.com/asyncapi/spec/issues/1038#issuecomment-1969489452
2. Open it in AsyncAPI studio
3. See the error: 66:11    error  asyncapi-schema-examples   "0" property type must be object components.schemas.io.github.springwolf.examples.kafka.dtos.XmlPayloadDto.examples[0]

**Related issue(s)**
- https://github.com/asyncapi/parser-js/issues/997
- https://github.com/stoplightio/spectral/issues/2624

### CODE REVIEW

**Comment by timonback** [comment]
Bump.

To resolve https://github.com/asyncapi/parser-js/issues/997#issuecomment-2367036182

Aligns with spectral parser, where the change has been merged via https://github.com/stoplightio/spectral/pull/2625#event-14518858703 and was approved by @jonaslagoni

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Just some linting problems :v:

**Comment by timonback** [comment]
> Just some linting problems ✌️

Thanks, PR is updated

**Review by jonaslagoni — APPROVED** [review]

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
As the new setup, you need to add a changeset 😓 https://github.com/asyncapi/parser-js/pull/1007#issuecomment-2451585051

**Review by jonaslagoni — APPROVED** [review]
Just merging it, at some point a change request will be added :shrug:

**Pull request merged**
