### PR TITLE
fix: allSchemas to return all schemas

### PR DESCRIPTION
**Pull request by jonaslagoni**
Solving https://github.com/asyncapi/parser-js/issues/39

### CODE REVIEW

**Comment by jonaslagoni** [comment]
The implementation is basically done, however the PR is blocked by https://github.com/asyncapi/parser-js/issues/42.

**Comment by jonaslagoni** [comment]
After implementing https://github.com/asyncapi/parser-js/pull/43 I realized that we might get quite a few `uid` duplicates, how can we handle that in regards to the `allSchemas` function? 🤔

**Comment by hesyar** [comment]
We have the same issue in our company, when will this PR  be merged?

**Comment by jonaslagoni** [comment]
@hesyar as soon as im done with https://github.com/asyncapi/parser-js/pull/43 😄

**Pull request merged**
