### PR TITLE
fix: remove forceful normalization of YAML to JSON

### PR DESCRIPTION
**Pull request by aeworxet**
This PR removes forceful normalization of YAML files to JSON format to fix https://github.com/asyncapi/parser-js/issues/936, which in its turn lays the foundation for reporting correct `range` values in error diagnostics for YAML files in `Studio`.

Related to https://github.com/asyncapi/parser-js/issues/1012

### CODE REVIEW

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by smoya** [comment]
@aeworxet it would be worth adding a comment in https://github.com/asyncapi/parser-js/blob/master/packages/parser/src/validate.ts#L49 mentioning Spectral uses the https://github.com/stoplightio/yaml parser, and basically, JSON is a valid YAML doc, so no matters if you pass YAML or JSON, that YAML parser will be able to parse it.

Additionally, please add two new unit tests in for the validate method testing at least one string input for JSON and another for YAML.

**Comment by aeworxet** [comment]
Updated PR.

**Comment by aeworxet** [comment]
Credits for the pack of changes in `packages/parser/test/parse.spec.ts` go to `eslint --fix`; otherwise, Sonar complained.

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Pull request merged**
