### PR TITLE
docs: updated the readme logo (#490)

### PR DESCRIPTION
**Pull request by heysolomon**
**Description**

- docs: updated the README.md (#490)
- new-logo
- I have changed the logo from the old one to the new one

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
@heysolomon thanks. With this new logo we can actually get rid of this entire HTML between line 1-9. Please use markdown to embed the logo, not `<a>`

**Review by magicmatatjahu — CHANGES_REQUESTED** [review]
You should use on Markdown without HTML and do other things. Please read action points of the issue https://github.com/asyncapi/parser-js/issues/490#issue-1166451595

So content should look like:

```md
[![AsyncAPI JavaScript Parser](./assets/logo.png)](https://www.asyncapi.com)

Use this package to parse and validate AsyncAPI documents —either YAML or JSON— in your Node.js or browser application. Updated bundle for the browser is always attached to the GitHub Release.
```

and please change name of file `new-brand.png` to the `logo.png`.

**Comment by heysolomon** [comment]
> @heysolomon thanks. With this new logo we can actually get rid of this entire HTML between line 1-9. Please use markdown to embed the logo, not `<a>`

@derberg  Okay, thanks. Let me correct that

**Comment by heysolomon** [comment]
@magicmatatjahu Thank you. Let me correct that

**Comment by heysolomon** [comment]
@derberg @magicmatatjahu i have just made the correction faf2b72d9f34c23ce5a3e3b8ccc2e294e25c9b59

**Comment by derberg** [comment]
@heysolomon hey, I think you missed `and please change name of file new-brand.png to the logo.png.` comment from @magicmatatjahu

**Comment by heysolomon** [comment]
> @heysolomon hey, I think you missed `and please change name of file new-brand.png to the logo.png.` comment from @magicmatatjahu

@derberg done f017ce1c1c221b89225b5893d06f04f0b92f93ab

**Review by magicmatatjahu — APPROVED** [review]
LGTM! Thanks for contribution!

**Comment by heysolomon** [comment]
> LGTM! Thanks for contribution!

Thank you! :)

**Pull request merged**
