### PR TITLE
chore: merge master into next major spec

### PR DESCRIPTION
**Pull request by fmvilas**
I'm merging the `master` branch into `next-major-spec` and fixing all the conflicts 😅

### CODE REVIEW

**Comment by fmvilas** [comment]
Can someone guess why `npm test` is failing? It complains that `cross-env` is not installed but it's on the package.json file. And it's running well on my machine 🤔

**Comment by smoya** [comment]
> Can someone guess why `npm test` is failing? It complains that `cross-env` is not installed but it's on the package.json file. And it's running well on my machine 🤔 

For some reason, we are not catching errors on npm install step. There are some in this case https://github.com/asyncapi/parser-js/actions/runs/5257292254/jobs/9500449903#step:8:2227

**Comment by fmvilas** [comment]
Good catch! I found it on my system by deleting node_modules. It's a corrupt package-lock.json file. I'm pushing a new one.

**Comment by jonaslagoni** [comment]
> `master` doesn't but `next-major-spec` does. This PR is not only merging `master` but also fixing the problems that appeared after doing that. What you see is that, the changes that I had to do to make it work after merging.

Ahhh, gotcha 👍

**Review by jonaslagoni — APPROVED** [review]
✅

**Comment by jonaslagoni** [comment]
REMEMBER TO MERGE COMMIT

**Comment by jonaslagoni** [comment]
> 🎉 This PR is included in version 2.0.3 🎉
> 
> The release is available on:
> 
>     * [npm package (@latest dist-tag)](https://www.npmjs.com/package/@asyncapi/parser/v/2.0.3)
> 
>     * [GitHub release](https://github.com/asyncapi/parser-js/releases/tag/v2.0.3)
> 
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Huh?

**Comment by fmvilas** [comment]
Weird 🤔 @KhudaDad414 you're the most familiar with GitHub actions along with Lukasz. Any idea what's happening?

**Comment by KhudaDad414** [comment]
I am assuming it's because of this comment. https://github.com/asyncapi/parser-js/pull/717#issuecomment-1591116967 🤔
commit are not included in the release(no possible 😆 ) so I guess we can ignore.

**Comment by fmvilas** [comment]
Are you saying that a comment triggered the release? o.O

**Comment by KhudaDad414** [comment]
The release isn't triggered for this branch. It's just a mistrigrered comment.

**Pull request merged**
