### PR TITLE
feat: add x-parser-spec-parsed extension

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Add `x-parser-spec-parsed: true` extension to root of parsed spec, similar like `x-parser-message-parsed` to avoid unnecessary calculations. I have use case when I stringify parsed spec (see [issue](https://github.com/asyncapi/parser-js/issues/266)) and after stringification I must pass this spec again to `AsyncAPIDocument` constructor. Also I fixed bug, because when we are assigning anonymous id of anonymous message we should first check that id is defined - for schemas we do it. 

**Related issue(s)**
See https://github.com/asyncapi/html-template/pull/166#pullrequestreview-642090407 especially part with:

> also this anonymous-message-1 should not be there 🤔 maybe my messages do not have name prop or title but they are in components and the key name should be applied right?

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
lgtm, can you just please add some comment [here](https://github.com/asyncapi/parser-js/pull/288/files#diff-a76417acabb91ce292a6285966f525f516f90be36426823ad0e410ce8c81e901R43) so we do not have to dig in the history later on to figure out why we assign this prop. 

Tbh, we already have so many parser specific extensions that I think it is about time to think about documenting them 😅 what do you think?

**Comment by derberg** [comment]
also, tests are failing and sonarcloud complains, have a look

**Comment by magicmatatjahu** [comment]
@derberg Thanks! I will fix tests and sonar clouds errors (I wrote PR yesterday about 23pm 😅).

> Tbh, we already have so many parser specific extensions that I think it is about time to think about documenting them 😅 what do you think?

Something like that?

```md
## Custom extensions

Parser during validation and parsing adds custom extensions (started by `x-parser`) that add additional information about the specification:

| Name | Value | Location | Description |
|---|---|---|
| `x-parser-spec-parsed` | `true` | Root of parsed specification | Indicates that specifixation is parsed |
```

**Comment by derberg** [comment]
> I wrote PR yesterday about 23pm 

then maybe I should actually do a deeper code review 🤔 😆 

for the docs, you went to far, just add a comment in code, readme is something for a followup, don't spend to much on it now, just open an issue if you want

**Review by derberg — APPROVED** [review]

**Pull request merged**
